const { chromium } = require('C:/Users/xpatt/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:8080');await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:'tmp/desktop.png',fullPage:true});
 assert.equal(await page.locator('.tool-card').count(),4);
 assert.deepEqual(await page.locator('.tool-card h3').allTextContents(),['Staging Tool','Key Performance Indicators','Shared Experiences and Action Plan','SOPs']);
 const links=await page.locator('.tool-card a.card-bottom').evaluateAll(els=>els.map(a=>a.href));
 assert.equal(links.length,4);
 assert(links[0].startsWith('https://uhacentral.com/'));
 assert.equal(links.some(href=>href.includes('drive.google.com')),false);
 assert.equal(await page.locator('a.drive-link').getAttribute('href'),'https://drive.google.com/drive/folders/1EwPBAMrvi6Ep32qMVQJxEsASAhSRi8fE');
 assert.match(await page.locator('.access-code code').textContent(),/^\$q9iNC!/);
 assert.equal(await page.locator('#sequence .guide-step').count(),6);
 assert.equal(await page.locator('.quick-links-bar, .chip, .quick-links-badge').count(),0);
 const media=await page.evaluate(()=>[...document.styleSheets].flatMap(s=>[...s.cssRules]).filter(r=>r.type===4).map(r=>r.conditionText));
 assert.equal(media.length,new Set(media).size,'Duplicate media queries');
 assert.equal(await page.locator('.deck-card').count(),6);
 const deckUrls=await page.locator('.deck-card').evaluateAll(els=>els.map(a=>a.getAttribute('href')));
 assert.equal(new Set(deckUrls).size,6,'Duplicate deck links');
 deckUrls.forEach(u=>assert.match(u,/^https:\/\/docs\.google\.com\/presentation\/d\/[\w-]+\/edit(\?|$)/,u));
 const deckTitles=await page.locator('.deck-card h3').allTextContents();
 assert.deepEqual(deckTitles,['Abridged Overview Activation presentation, 11 Sept 2026','Overview Integrated Delivery of Health Services-Sentinel','Sentinel Learning Sites Orientation, Sept 6 2026','Data Collection Tool Slides','Quality of Care','SOPs at Sentinel Sites']);
 const cloudUrls=await page.locator('a[href*="docs.google.com/document"]').evaluateAll(els=>els.map(a=>a.getAttribute('href')));
 assert.equal(cloudUrls.length,2,'Expected 2 cloud report links');
 assert.equal(new Set(cloudUrls).size,2,'Duplicate cloud report links');
 cloudUrls.forEach(u=>assert.match(u,/^https:\/\/docs\.google\.com\/document\/d\/[\w-]+\/edit(\?|$)/,u));
 await page.locator('nav a[href="#resources"]').click();
 assert.equal(await page.locator('.resource').count(),14);
 await page.locator('#resource-search').fill('staging');assert(await page.locator('.resource').count()>0);
 await page.locator('#resource-category').selectOption('Assessment');assert.equal(await page.locator('.resource').count(),4);
 await page.locator('#resource-search').fill('zzzzzz');assert.equal(await page.locator('.empty').count(),1);
 await page.locator('#clear-search').click();assert.equal(await page.locator('.resource').count(),14);
 await page.locator('#resource-category').selectOption('Reporting');assert.equal(await page.locator('.resource').count(),2);
 await page.locator('#resource-category').selectOption('');
 const files=await page.evaluate(()=>window.SENTINEL_DATA.resources.map(r=>r.url));
 for(const f of files){assert(fs.existsSync(path.join('dist',f)),f);const response=await page.request.get('http://localhost:8080/'+f);assert.equal(response.status(),200,f);}
 await page.locator('nav a[href="#checklist"]').click();
 await page.locator('[data-check="0"]').check();await page.reload();assert(await page.locator('[data-check="0"]').isChecked());
 for(let i=1;i<8;i++)await page.locator(`[data-check="${i}"]`).check();
 assert.match(await page.locator('#progress-label').textContent(),/8 of 8/);
 page.once('dialog',d=>d.accept());await page.locator('#reset-checklist').click();assert.match(await page.locator('#progress-label').textContent(),/0 of 8/);
 await page.locator('nav a[href="#guide"]').click();assert.equal(await page.locator('.guide-step').count(),6);
 await page.locator('.guide-step').nth(5).locator('summary').click();assert(await page.locator('.guide-step').nth(5).getAttribute('open')!==null);
 await page.locator('nav a[href="#teams"]').click();
 assert.equal(await page.locator('.team-card, .roster, #region-filter').count(),0);
 assert.equal(await page.locator('.day-card').count(),5);
 assert.equal(await page.evaluate(()=>Object.hasOwn(window.SENTINEL_DATA,'teams')),false);
 assert.equal((await page.request.get('http://localhost:8080/resources/phase-3-team-allocations.csv')).status(),404);
 assert.equal(await page.locator('a[href*="drive.google.com"]').count(),0);
 await page.screenshot({path:'tmp/teams.png',fullPage:true});
 for(const width of [390,768,1440]){
  await page.setViewportSize({width,height:900});
  for(const view of ['overview','guide','resources','checklist','teams']){
   await page.goto('http://localhost:8080/#'+view);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Horizontal overflow: ${view} ${width}`);
   if(width===390)await page.screenshot({path:`tmp/mobile-${view}.png`,fullPage:true});
  }
 }
 await page.setViewportSize({width:1280,height:900});await page.goto('http://localhost:8080/#overview');
 await page.evaluate(()=>document.documentElement.style.fontSize='32px');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200% font overflow');
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: all 5 views, 14 downloads, resource search/filter/empty state, checklist persistence/reset, confidential roster removal, guide disclosure, 3 viewport widths and 200% font sizing. No JavaScript errors.');
})().catch(e=>{console.error(e);process.exit(1)});
